### ISSUE TITLE
The test for #adding_matz is incomplete.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/simple-nesting#22]
Hello. The test for #adding_matz checks to see that a :yukihiro_matsumoto key is added to the programmer_hash. 

However, according to the comments in that method, the value of programmer_hash[:yukihiro_matsumoto] should be 
{ 
   :known_for => "Ruby",
   :languages => ["LISP", "C"]
}

The problem is that there is no test to check for that.

Thanks for looking into this issue!
Sdcrouse

**Comment by cjbrock** [comment]
Hey @Sdcrouse! The choice to check only for the keys in this case was actually intentional. As you've probably noticed, testing frameworks can be a bit brittle on things like spaces. Because the programmer hash is actually
`{
        :grace_hopper => {
          :known_for => "COBOL",
          :languages => ["COBOL", "FORTRAN"]
        },
        :alan_kay => {
          :known_for => "Object Orientation",
          :languages => ["Smalltalk", "LISP"]
        },
        :dennis_ritchie => {
          :known_for => "Unix",
          :languages => ["C"]
        }
     }`

you can see how many different variations you might get with the spacing. By only checking for the keys, we eliminate a lot of student frustration. 

As a side note, I've noticed you've been taking a lot of your time to make pull requests to help make the curriculum better, and I really appreciate it. Not a lot of people do that, so thank you. 

// Corinna

**Comment by Sdcrouse** [comment]
You're welcome! Glad to help!

Sdcrouse
